project:
  type: website

website:
  title: "City Nature Challenge Austria"
  search: false
  description: "Auswertungen und Analyse für die iNaturalist City Nature Challenge in Österreich."
  repo-url: "https://github.com/HannesOberreiter/inat-austria-city-challenge-2023"
  repo-actions: "edit"
  navbar:
    left:
      - href: graz2023.qmd
        text: "Graz"
      - href: graz2022.qmd
        text: "Graz 2022 (Demo)"
      - href: about.qmd
        text: "About"

format:
  html:
    link-external-icon: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
